# Generated by Django 6.0.6 on 2026-06-20 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamOfficials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_teacher', models.CharField(blank=True, max_length=100)),
                ('head_of_academics', models.CharField(blank=True, max_length=100)),
                ('head_teacher', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='academic.stream')),
            ],
            options={
                'db_table': 'stream_officials',
            },
        ),
    ]
